name: jordanredshaw
favicon: null
layout_spectrum: 0.5804179783444852
typography_spectrum: 0.5301260040141642
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.21160718868486583
  lightness: 0.11023029149509966
  saturation: 0.21283937082625926
  rhythmicContrast: 0.438530559418723
purpose: []
