name: jordanredshaw
favicon: null
layout_spectrum: 0.99656
typography_spectrum: 0.53689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#d6d6d6'
    - '#3f3b3a'
    - '#010101'
    - '#999491'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
