name: jordanredshaw
favicon: null
layout_spectrum: 0.5804179783444852
typography_spectrum: 0.53689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0e8279'
    - '#c9dbdf'
    - '#223c3d'
    - '#72a79f'
  brandStrength: 1
  lightness: 0.11023029149509966
  saturation: 0.21283937082625926
  rhythmicContrast: 0.438530559418723
purpose: []
